version: '1.0'
protectables:
    - ANVIL
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    - BEACON
    - BREWING_STAND
    - CHEST
    - CAULDRON
    - COMPARATOR
    - REPEATER
    - DISPENSER
    - DROPPER
    - OAK_FENCE_GATE
    - FURNACE
    - HOPPER
    - JUKEBOX
    - NOTE_BLOCK
    - LEVER
    - STONE_BUTTON
    - OAK_TRAPDOOR
    - BIRCH_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - TRAPPED_CHEST
    - OAK_BUTTON
    - BIRCH_BUTTON
    - SPRUCE_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - IRON_TRAPDOOR
    - ACACIA_FENCE_GATE
    - BIRCH_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - ACACIA_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - OAK_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - STONE_PRESSURE_PLATE
    - BARREL
    - BELL
    - BLAST_FURNACE
    - CAMPFIRE
    - COMPOSTER
    - DAYLIGHT_DETECTOR
    - LECTERN
    - SMOKER
    - BEEHIVE
    - BEE_NEST
    - CRIMSON_PRESSURE_PLATE
    - WARPED_PRESSURE_PLATE
    - CRIMSON_TRAPDOOR
    - WARPED_TRAPDOOR
    - CRIMSON_BUTTON
    - WARPED_BUTTON
    - POLISHED_BLACKSTONE_BUTTON
    - POLISHED_BLACKSTONE_PRESSURE_PLATE
    - RESPAWN_ANCHOR
    - CRIMSON_DOOR
    - CRIMSON_FENCE_GATE
    - WARPED_DOOR
    - WARPED_FENCE_GATE
    - MANGROVE_BUTTON
    - MANGROVE_DOOR
    - MANGROVE_FENCE_GATE
    - MANGROVE_PRESSURE_PLATE
    - MANGROVE_TRAPDOOR
    - CHERRY_BUTTON
    - CHERRY_DOOR
    - CHERRY_FENCE_GATE
    - CHERRY_PRESSURE_PLATE
    - CHERRY_TRAPDOOR
    - BAMBOO_BUTTON
    - BAMBOO_DOOR
    - BAMBOO_FENCE_GATE
    - BAMBOO_PRESSURE_PLATE
    - BAMBOO_TRAPDOOR
    - CHISELED_BOOKSHELF
    - COPPER_DOOR
    - EXPOSED_COPPER_DOOR
    - OXIDIZED_COPPER_DOOR
    - WAXED_COPPER_DOOR
    - WAXED_EXPOSED_COPPER_DOOR
    - WAXED_OXIDIZED_COPPER_DOOR
    - WAXED_WEATHERED_COPPER_DOOR
    - WEATHERED_COPPER_DOOR
    - COPPER_TRAPDOOR
    - EXPOSED_COPPER_TRAPDOOR
    - OXIDIZED_COPPER_TRAPDOOR
    - WAXED_COPPER_TRAPDOOR
    - WAXED_EXPOSED_COPPER_TRAPDOOR
    - WAXED_OXIDIZED_COPPER_TRAPDOOR
    - WAXED_WEATHERED_COPPER_TRAPDOOR
    - WEATHERED_COPPER_TRAPDOOR
    - CRAFTER
    - DECORATED_POT
    - PALE_OAK_BUTTON
    - PALE_OAK_DOOR
    - PALE_OAK_FENCE_GATE
    - PALE_OAK_PRESSURE_PLATE
    - PALE_OAK_TRAPDOOR
tool: STICK
chatprefix: SL
populateplayers: false